language: python
python:
  - "3.5"
jobs:
  include:
    - stage: integrity_tests
      install:
        - pip install -r integrity_tests/requirements.txt
      script:
        - airflow initdb
        # Add a dummy environment file to make the dag valid
        - echo "prd" > dags/environment.conf
        - coverage run -m pytest integrity_tests/*
    - stage: mock_pipeline_tests
      install:
        - pip install -r mock_pipeline_tests/requirements.txt
      script:
        - coverage run -m pytest mock_pipeline_tests/*