language: python
python:
  - "3.5"
jobs:
  include:
    - stage: integrity_tests
      install:
        - pip install -r integrity_tests/requirements.txt
      script:
        - airflow initdb
        - coverage run -m pytest integrity_tests/*
    - stage: mock_pipeline_tests
      script:
        - echo "HELLO"